[package]
name = "rust-proto-repo-template"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tonic = "0.8.1"
prost = "0.11.0"

[build-dependencies]
walkdir = "2.3.2"
tonic-build = "0.8.0"
